// SIZING ACTIONS

export const ADD_SIZING = 'ADD_SIZING'
export const DEL_SIZING = 'DEL_SIZING'
export const SAVE_SIZING = 'SAVE_SIZING'
export const GEN_SIZING = 'GEN_SIZING'

// SIZING SETTING ACTIONS

export const ADD_SIZING_SETTING = 'ADD_SIZING_SETTING'
export const DEL_SIZING_SETTING = 'DEL_SIZING_SETTING'
export const SAVE_SIZING_SETTING = 'SAVE_SIZING_SETTING'

// RATING ACTIONS

export const ADD_RATING = 'ADD_RATING'
export const DEL_RATING = 'DEL_RATING'
export const SAVE_RATING = 'SAVE_RATING'
export const GEN_RATING = 'GEN_RATING'

// RATING SETTING ACTIONS

export const ADD_RATING_SETTING = 'ADD_RATING_SETTING'
export const DEL_RATING_SETTING = 'DEL_RATING_SETTING'
export const SAVE_RATING_SETTING = 'SAVE_RATING_SETTING'