// SIZING ACTIONS

export const ADD_SIZING = 'ADD_SIZING'
export const DEL_SIZING = 'DEL_SIZING'
export const EDIT_SIZING = 'EDIT_SIZING'
export const GEN_SIZING = 'GEN_SIZING'

// SIZING PLAN ACTIONS

export const ADD_SIZING_PLAN = 'ADD_SIZING_PLAN'
export const DEL_SIZING_PLAN = 'DEL_SIZING_PLAN'
export const EDIT_SIZING_PLAN = 'EDIT_SIZING_PLAN'

// RATING ACTIONS

export const ADD_RATING = 'ADD_RATING'
export const DEL_RATING = 'DEL_RATING'
export const EDIT_RATING = 'EDIT_RATING'
export const GEN_RATING = 'GEN_RATING'

// RATING PLAN ACTIONS

export const ADD_RATING_PLAN = 'ADD_RATING_PLAN'
export const DEL_RATING_PLAN = 'DEL_RATING_PLAN'
export const EDIT_RATING_PLAN = 'EDIT_RATING_PLAN'